### ISSUE TITLE
Error in load() in wider_face.py when no faces are reported for an image

### ISSUE THREAD

**Issue by rogerhcheng** [varunagrawal/tiny-faces-pytorch#10]
There will be an error in load() in wider_face.py when no faces are reported for an image.  This code starting from line 75 will fix the problem:

                if n == 0:
                    idx += 1
                else:
                    for b in range(n):
                        bboxes[b, :] = [abs(float(x))
                                        for x in lines[idx].strip().split()]
                        idx += 1

**Comment by varunagrawal** [comment]
Hi @rogerhcheng. Can you please make a PR of your code? I can review it and merge it in. Thanks!

**Comment by rogerhcheng** [comment]
Hi @varunagrawal , I get the following error below when I try to push my private branch.  Do I either need permission from you, or is there some alternative method I can use?  Thanks! 

E:\Baseball\tiny-faces-pytorch>git push --set-upstream origin rogerhcheng/fix_wider_face_load
remote: Permission to varunagrawal/tiny-faces-pytorch.git denied to rogerhcheng.
fatal: unable to access 'https://github.com/varunagrawal/tiny-faces-pytorch.git/': The requested URL returned error: 403

**Comment by rogerhcheng** [comment]
Hi @varunagrawal , I finally remembered to create the pull request from my forked branch.  Please let me know if you have any comments.  Thanks.

**Comment by varunagrawal** [comment]
Merged in! Thanks again.
