### ISSUE TITLE
On new test image, no output

### ISSUE THREAD

**Issue by darshangera** [varunagrawal/tiny-faces-pytorch#11]
Hi, I want to use this code for detecting faces for some other application. I tried detecting on a sample face attached image. But it gives 0 faces on same. I have resized image to lower resolution of 1024x768 and tested. 
![DSC_0476](https://user-images.githubusercontent.com/16755171/70319203-bc5a4a80-1847-11ea-89c8-f0a32dda00c1.JPG)

Can you please see what could be the issue?
Thanks.

**Comment by varunagrawal** [comment]
I'll try my trained model on your image in a few days. Thank you for your patience.

**Comment by hamzakhalil798** [comment]
@varunagrawal do you have any visualization script?

**Comment by varunagrawal** [comment]
There might be something in the repo. I don't remember off the top of my head. Either way, if you have the bounding boxes, it should be straightforward to plot it on the image.

**Comment by hamzakhalil798** [comment]
@varunagrawal Thankyou I found it.
Although the results aren't satisfactory with the 50 epochs model ,  do you have a more trained model?
If yes kindly share.

**Comment by varunagrawal** [comment]
Sorry I don't have the resources currently to train a new model.

**Comment by hamzakhalil798** [comment]
@varunagrawal  Okay , No issues  thankyou..😀

**Comment by varunagrawal** [comment]
Apologies for the very delayed response. I retrained the model and with the latest uploaded weights, I get the following result. Not bad huh?

![test_img_result](https://github.com/varunagrawal/tiny-faces-pytorch/assets/975964/04aa8d8c-67ea-46d9-b75c-79294a7e7578)

To reproduce, please use the `detect_image.py` script with `--prob_thresh=0.6` and `--nms_thresh=0.3`.
