### ISSUE TITLE
RuntimeError: DefaultCPUAllocator: not enough memory:Buy new RAM!

### ISSUE THREAD

**Issue by sslcheese** [varunagrawal/tiny-faces-pytorch#12]
Thanks for your contribution!
I have a problem that program remind me 
"RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 113246208 bytes. Buy new RAM!"
I use my laptop with 8G memory.(windows)
So I want to know how much memory did you use? And  is Virtual memory useful?

**Comment by varunagrawal** [comment]
My desktop has 16 gb of RAM but I also have a GPU where I run all my experiments on. I would recommend setting the batch size for training to half the current value.
