### ISSUE TITLE
No matching distribution found for sklearn==0.20.1

### ISSUE THREAD

**Issue by sahmed130** [varunagrawal/tiny-faces-pytorch#14]
All the required packages are not installed as some of them were missing.

![image](https://user-images.githubusercontent.com/57598108/71765063-c7210180-2f11-11ea-9763-7487a9927b0b.png)

**Comment by varunagrawal** [comment]
Ugh that's because scikit-learn has different names. That's really annoying, let me see what I can do.

**Comment by varunagrawal** [comment]
Updated `requirements.txt`. Thanks for reporting this.
