### ISSUE TITLE
Run on external image/video

### ISSUE THREAD

**Issue by fabiozappo** [varunagrawal/tiny-faces-pytorch#16]
Hi thank you really much for your work on this Pytorch version!

I would like to run the code on a single external image/video. Does your code provide a demo as the original one?

**Comment by rabysam28** [comment]
@varunagrawal @rogerhcheng 
I wanted to follow up on this ticket, since I also am interested in just testing one single external image to see how it works for my cases. Is there a python demo script for this? Thanks

**Comment by varunagrawal** [comment]
I can add a python demo script next week. Sorry I don't get issue notifications from github for some reason.

**Comment by gdiasbruno** [comment]
Hey @varunagrawal ,

First of all, thanks a lot for your amazing work! It will help me in my master thesis
 
Do you have a script? If you do, amazing, but I see it is also possible to create one from the evaluation script.

Thanks a lot, again!

**Comment by varunagrawal** [comment]
The `trainer.py` module has a function called `get_detections` which is what you're looking for.

I am in the process of refactoring the codebase so expect things to change. I intend to add a more straightforward means of deploying the model.

**Comment by varunagrawal** [comment]
@fabiozappo see the `evaluate.py` script. It evaluates on the test dataset, but you can see that the `get_detections` method takes an image tensor as input.

Closing this issue.
