### ISSUE TITLE
Several collections and issues

### ISSUE THREAD

**Issue by tongxiaozhong14** [varunagrawal/tiny-faces-pytorch#20]
![Uploading 捕获.PNG…]()
usage: Model Evaluator [-h] [--split SPLIT] [--dataset-root DATASET_ROOT]
                       [--checkpoint CHECKPOINT] [--prob_thresh PROB_THRESH]
                       [--nms_thresh NMS_THRESH] [--workers WORKERS]
                       [--batch_size BATCH_SIZE] [--results_dir RESULTS_DIR]
                       [--debug]
                       dataset
Model Evaluator: error: argument --checkpoint: expected one argument
What kind of installation do you request?

**Comment by varunagrawal** [comment]
The checkpoint is the path to the pretrained model. At the very least it should be an ImageNet trained model?

**Comment by varunagrawal** [comment]
Checkpoint should be the path to a pretrained model. It is optional of course.

**Comment by varunagrawal** [comment]
Also, I can't see the screenshot. Can you please upload it again? Or even better, copy-paste the full error?

**Comment by varunagrawal** [comment]
Closing due to lack of a response.
