### ISSUE TITLE
Visualize result

### ISSUE THREAD

**Issue by toti-bz** [varunagrawal/tiny-faces-pytorch#30]
is there a way to visualize the predictions?

**Comment by hamzakhalil798** [comment]
@toti-bz 
Did you find any solution?

**Comment by varunagrawal** [comment]
Torchvision has a method called [draw_bounding_box](https://pytorch.org/vision/main/generated/torchvision.utils.draw_bounding_boxes.html) that might be useful in this case. Else, OpenCV has lots of examples of drawing bounding boxes in images.
