### ISSUE TITLE
Can you please provide the trained weights and demo script?

### ISSUE THREAD

**Issue by ghost** [varunagrawal/tiny-faces-pytorch#5]

**Comment by varunagrawal** [comment]
Here you go: https://drive.google.com/open?id=1V8c8xkMrQaCnd3MVChvJ2Ge-DUfXPHNu

Loading these weights and running evaluation should be straightforward. Please take a look at the `evaluate.py` file.

**Comment by ghost** [comment]
Thanks a lot, @varunagrawal
