### ISSUE TITLE
cannot import name 'jaccard_index' from 'utils.metrics'

### ISSUE THREAD

**Issue by Jianyuyu5666** [varunagrawal/tiny-faces-pytorch#7]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from datasets import get_dataloader
  File "/home/ivdai/Gene/tiny-faces-pytorch/datasets/__init__.py", line 5, in <module>
    from utils.cluster import compute_kmedoids
  File "/home/ivdai/Gene/tiny-faces-pytorch/utils/cluster.py", line 14, in <module>
    from .metrics import jaccard_index, rect_dist
ImportError: cannot import name 'jaccard_index' from 'utils.metrics' (/home/ivdai/Gene/tiny-faces-pytorch/utils/metrics.py)
Makefile:12: recipe for target 'main' failed
make: *** [main] Error 1

You forget to update your cluster.py under utils dir

**Comment by QuantumBird** [comment]
Yes, I found the same question when I run evaluate.py, I opened metrics.py and found nothing about "jaccard_index"........

**Comment by xingfan-git** [comment]
I have the same problem. I guess the author want to calculate the Jaccard similarity score of two bounding boxes, but I am confused with the third parameter passing to the function. Could you tell me what's the function of the last pair variable (i, j) for please?
@varunagrawal

**Comment by varunagrawal** [comment]
I have added the `jaccard_index` function back. The code should work now.
