### ISSUE TITLE
RuntimeError: DataLoader worker (pid 3176) is killed by signal: Killed. 

### ISSUE THREAD

**Issue by xingfan-git** [varunagrawal/tiny-faces-pytorch#8]
@varunagrawal 
Hi, I got an error:
"RuntimeError: DataLoader worker (pid 3176) is killed by signal: Killed. 
Makefile:12: recipe for target 'main' failed
make: *** [main] Error 1"
when I make the files.
It seems occur when the model try to begin training.

Could someone help me out please?

**Comment by varunagrawal** [comment]
Is your dataset set up correctly? This doesn't seem related to the code.
